### PR TITLE
Remove go 1.7.5

### PR DESCRIPTION
**Pull request by sulthonzh**

### CODE REVIEW

**Comment by raphael** [comment]
Can you please add Go 1.9 and 1.10 to the list?

**Comment by sulthonzh** [comment]
@raphael hi, i have test with go 1.10, but not working well, go1.10 has detected go 1.1, i don't why,

**Comment by tchssk** [comment]
https://docs.travis-ci.com/user/languages/go/

> Note that, in order to choose Go 1.10, you must use go: "1.10" (a string), not go: 1.10 (a float). Using a float results in the use of Go 1.1.

**Comment by raphael** [comment]
Looks good, one last thing: please use "1.8.x", "1.9.x" and "1.10.x" so Travis uses the latest versions instead of the first build of each minor version. Thank you!

**Pull request closed without merging**
